### ISSUE TITLE
Does `conv_codes_benchmark.py` use rate-1/2 RSC code?

### ISSUE THREAD

**Issue by datlife** [yihanjiang/Sequential-RNN-Decoder#1]
Hi @yihanjiang ,

I am an undergraduate student trying to reproduce your paper result. I wonder if the `conv_codes_benchmark.py` uses rate-1/2 RSC Code. Particularly, I am talking about the following line:

```
# Line 70, `conv_codes_benchmark.py`
trellis1 = cc.Trellis(M, generator_matrix,feedback=feedback)
```
According the [CommPy](https://github.com/veeresht/CommPy/blob/master/commpy/channelcoding/convcode.py#L352) documentation, we need to set `code_type='rsc'`. However, I don't see it:

Regads,
Dat

**Comment by yihanjiang** [comment]
Hi Dat,

Sorry for missing this issue for a long time, I used another github account, and forget to deal with the issue in this repo. Both rsc and non-rsc is supported in Commpy, so I did the default version. We find both rsc and non-rsc, LSTM has similar performance comparing to Conv code.

Thanks, and nice job on the unofficial repo!

Yihan
